// <auto-generated />
using System;
using Lab1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lab1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909111625_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lab1.Model.AlmanacBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlmanacId")
                        .HasColumnType("integer");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlmanacId");

                    b.ToTable("AlmanacBooks", (string)null);
                });

            modelBuilder.Entity("Lab1.Model.LibraryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PublishYear")
                        .HasColumnType("integer");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LibraryItems", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Lab1.Model.NewspaperColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("JournalistName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NewspaperId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NewspaperId");

                    b.ToTable("NewspaperColumns", (string)null);
                });

            modelBuilder.Entity("Lab1.Model.Almanac", b =>
                {
                    b.HasBaseType("Lab1.Model.LibraryItem");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer");

                    b.ToTable("Almanacs", (string)null);
                });

            modelBuilder.Entity("Lab1.Model.Book", b =>
                {
                    b.HasBaseType("Lab1.Model.LibraryItem");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer");

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("Lab1.Model.Newspaper", b =>
                {
                    b.HasBaseType("Lab1.Model.LibraryItem");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("Newspapers", (string)null);
                });

            modelBuilder.Entity("Lab1.Model.AlmanacBook", b =>
                {
                    b.HasOne("Lab1.Model.Almanac", "Almanac")
                        .WithMany("Books")
                        .HasForeignKey("AlmanacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Almanac");
                });

            modelBuilder.Entity("Lab1.Model.NewspaperColumn", b =>
                {
                    b.HasOne("Lab1.Model.Newspaper", null)
                        .WithMany("Columns")
                        .HasForeignKey("NewspaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lab1.Model.Almanac", b =>
                {
                    b.HasOne("Lab1.Model.LibraryItem", null)
                        .WithOne()
                        .HasForeignKey("Lab1.Model.Almanac", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lab1.Model.Book", b =>
                {
                    b.HasOne("Lab1.Model.LibraryItem", null)
                        .WithOne()
                        .HasForeignKey("Lab1.Model.Book", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lab1.Model.Newspaper", b =>
                {
                    b.HasOne("Lab1.Model.LibraryItem", null)
                        .WithOne()
                        .HasForeignKey("Lab1.Model.Newspaper", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lab1.Model.Almanac", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Lab1.Model.Newspaper", b =>
                {
                    b.Navigation("Columns");
                });
#pragma warning restore 612, 618
        }
    }
}
